"""Wiki Vault — Obsidian-compatible markdown export of the knowledge graph.

Renders each entity as a ``.md`` file with YAML frontmatter and
``[[wiki-links]]`` for Obsidian backlinks.  Bidirectional: Thoth writes
the vault, users can edit in Obsidian, and changes sync back.

Vault structure::

    vault/
    ├── wiki/                  ← one .md per entity (by type sub-folder)
    │   ├── person/
    │   │   ├── Mom.md
    │   │   └── _index.md      ← rollup of sparse entities
    │   ├── preference/
    │   ├── fact/
    │   ├── event/
    │   ├── place/
    │   ├── project/
    │   └── index.md           ← master index of all entities
    ├── conversations/         ← optional conversation exports
    └── raw/                   ← user-uploaded files for ingestion

Settings are stored in ``~/.thoth/wiki_config.json``.
"""

from __future__ import annotations

import json
import logging
import os
import pathlib
import re
import shutil
import threading
from datetime import datetime
from typing import Any

logger = logging.getLogger(__name__)

# ── Data / config paths ─────────────────────────────────────────────────────

_DATA_DIR = pathlib.Path(
    os.environ.get("THOTH_DATA_DIR", pathlib.Path.home() / ".thoth")
)
_CONFIG_PATH = _DATA_DIR / "wiki_config.json"

# Minimum description length for an entity to get its own .md file.
# Shorter entities go into _index.md rollup instead.
_MIN_CONTENT_LENGTH = 20

# Auto-generated header so users know not to hand-edit wiki files.
_AUTO_HEADER = "<!-- Auto-generated by Thoth — edits here sync back to the knowledge graph -->\n\n"

# ═════════════════════════════════════════════════════════════════════════════
# Configuration
# ═════════════════════════════════════════════════════════════════════════════

_DEFAULT_CONFIG: dict[str, Any] = {
    "enabled": False,
    "vault_path": str(_DATA_DIR / "vault"),
}

_config_lock = threading.Lock()


def _load_config() -> dict[str, Any]:
    """Load wiki vault config from disk, returning defaults on error."""
    if _CONFIG_PATH.exists():
        try:
            raw = _CONFIG_PATH.read_text(encoding="utf-8")
            cfg = json.loads(raw)
            # Merge with defaults for any missing keys
            merged = {**_DEFAULT_CONFIG, **cfg}
            return merged
        except (json.JSONDecodeError, OSError):
            pass
    return dict(_DEFAULT_CONFIG)


def _save_config(cfg: dict[str, Any]) -> None:
    """Persist wiki vault config to disk."""
    _DATA_DIR.mkdir(parents=True, exist_ok=True)
    with _config_lock:
        _CONFIG_PATH.write_text(
            json.dumps(cfg, indent=2), encoding="utf-8"
        )


def is_enabled() -> bool:
    """Return True if the wiki vault feature is turned on."""
    return _load_config().get("enabled", False)


def set_enabled(enabled: bool) -> None:
    """Toggle the wiki vault on or off."""
    cfg = _load_config()
    cfg["enabled"] = enabled
    _save_config(cfg)
    if enabled:
        _ensure_vault_dirs()


def get_vault_path() -> pathlib.Path:
    """Return the configured vault root as a Path."""
    return pathlib.Path(_load_config()["vault_path"])


def set_vault_path(path: str) -> None:
    """Change the vault root directory."""
    cfg = _load_config()
    cfg["vault_path"] = str(pathlib.Path(path).resolve())
    _save_config(cfg)
    if cfg.get("enabled"):
        _ensure_vault_dirs()


# ═════════════════════════════════════════════════════════════════════════════
# Vault directory management
# ═════════════════════════════════════════════════════════════════════════════

_WIKI_SUBDIRS = [
    "wiki/person", "wiki/preference", "wiki/fact", "wiki/event",
    "wiki/place", "wiki/project", "wiki/organisation", "wiki/concept",
    "wiki/skill", "wiki/media",
    "conversations", "raw",
]


def _ensure_vault_dirs() -> None:
    """Create the vault folder structure if it doesn't exist."""
    vault = get_vault_path()
    for sub in _WIKI_SUBDIRS:
        (vault / sub).mkdir(parents=True, exist_ok=True)


# ═════════════════════════════════════════════════════════════════════════════
# Filename helpers
# ═════════════════════════════════════════════════════════════════════════════

_UNSAFE_CHARS = re.compile(r'[<>:"/\\|?*\x00-\x1f]')


def _safe_filename(subject: str) -> str:
    """Convert an entity subject to a filesystem-safe filename (no extension)."""
    name = _UNSAFE_CHARS.sub("_", subject.strip())
    # Collapse multiple underscores
    name = re.sub(r"_+", "_", name).strip("_")
    # Limit length (filesystem safety)
    return name[:120] or "unnamed"


def _entity_md_path(entity: dict) -> pathlib.Path:
    """Return the expected .md path for an entity."""
    vault = get_vault_path()
    etype = entity.get("entity_type", "fact")
    fname = _safe_filename(entity.get("subject", "unnamed"))
    return vault / "wiki" / etype / f"{fname}.md"


# ═════════════════════════════════════════════════════════════════════════════
# Markdown rendering
# ═════════════════════════════════════════════════════════════════════════════

def _render_frontmatter(entity: dict) -> str:
    """Build YAML frontmatter for an entity."""
    props = entity.get("properties", "{}")
    if isinstance(props, str):
        try:
            props = json.loads(props)
        except (json.JSONDecodeError, TypeError):
            props = {}

    lines = [
        "---",
        f"id: {entity['id']}",
        f"type: {entity.get('entity_type', '')}",
        f"subject: \"{entity.get('subject', '')}\"",
    ]
    aliases = entity.get("aliases", "")
    if aliases:
        alias_list = [a.strip() for a in aliases.split(",") if a.strip()]
        lines.append(f"aliases: [{', '.join(repr(a) for a in alias_list)}]")
    tags = entity.get("tags", "")
    if tags:
        tag_list = [t.strip() for t in tags.split(",") if t.strip()]
        lines.append(f"tags: [{', '.join(repr(t) for t in tag_list)}]")
    if props:
        for k, v in props.items():
            lines.append(f"{k}: {json.dumps(v)}")
    lines.append(f"source: {entity.get('source', 'live')}")
    lines.append(f"created: {entity.get('created_at', '')}")
    lines.append(f"updated: {entity.get('updated_at', '')}")
    lines.append("---")
    return "\n".join(lines)


def _render_relations_section(entity_id: str) -> str:
    """Build a markdown section listing an entity's relations as wiki-links."""
    try:
        import knowledge_graph as kg
        rels = kg.get_relations(entity_id, direction="both")
    except Exception:
        return ""

    if not rels:
        return ""

    lines = ["\n## Connections\n"]
    for r in rels:
        peer = r.get("peer_subject", "?")
        link = f"[[{peer}]]"
        direction = r.get("direction", "outgoing")
        rtype = r.get("relation_type", "related_to")
        if direction == "outgoing":
            lines.append(f"- {rtype} → {link}")
        else:
            lines.append(f"- {link} → {rtype}")
    return "\n".join(lines)


def render_entity_md(entity: dict) -> str:
    """Render a full markdown document for an entity."""
    parts = [
        _AUTO_HEADER,
        _render_frontmatter(entity),
        "",
        f"# {entity.get('subject', 'Unnamed')}",
        "",
    ]

    desc = entity.get("description", "")
    if desc:
        parts.append(desc)
        parts.append("")

    rels = _render_relations_section(entity["id"])
    if rels:
        parts.append(rels)

    return "\n".join(parts) + "\n"


# ═════════════════════════════════════════════════════════════════════════════
# Index generation
# ═════════════════════════════════════════════════════════════════════════════

def _render_type_index(entity_type: str, entities: list[dict]) -> str:
    """Render a _index.md for a specific entity type.

    Contains wiki-links to full articles + inline entries for sparse entities.
    """
    lines = [
        _AUTO_HEADER.strip(),
        f"# {entity_type.title()}",
        "",
    ]

    full_entities = []
    sparse_entities = []

    for e in sorted(entities, key=lambda x: x.get("subject", "")):
        desc = e.get("description", "") or ""
        if len(desc) >= _MIN_CONTENT_LENGTH:
            full_entities.append(e)
        else:
            sparse_entities.append(e)

    if full_entities:
        for e in full_entities:
            subj = e.get("subject", "?")
            lines.append(f"- [[{subj}]]")
        lines.append("")

    if sparse_entities:
        lines.append("## Quick Notes")
        lines.append("")
        for e in sparse_entities:
            subj = e.get("subject", "?")
            desc = (e.get("description", "") or "").strip()
            lines.append(f"- **{subj}**: {desc}" if desc else f"- **{subj}**")
        lines.append("")

    return "\n".join(lines) + "\n"


def _render_master_index(all_entities: list[dict]) -> str:
    """Render the top-level wiki/index.md with counts and links."""
    from collections import Counter
    type_counts = Counter(e.get("entity_type", "fact") for e in all_entities)

    lines = [
        _AUTO_HEADER.strip(),
        "# Thoth Knowledge Base",
        "",
        f"**{len(all_entities)} entities** across {len(type_counts)} categories.",
        "",
    ]

    for etype, count in sorted(type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- [{etype.title()}]({etype}/_index.md) — {count}")
    lines.append("")

    return "\n".join(lines) + "\n"


def _refresh_type_index(entity_type: str) -> None:
    """Regenerate the _index.md for a single entity type.

    Called after a sparse entity is saved so it appears in the rollup
    immediately rather than waiting for a full ``rebuild_vault()``.
    """
    try:
        import knowledge_graph as kg
        entities = [
            e for e in kg.list_entities(limit=100_000)
            if e.get("entity_type") == entity_type
        ]
    except Exception:
        return

    vault = get_vault_path()
    idx_path = vault / "wiki" / entity_type / "_index.md"
    idx_path.parent.mkdir(parents=True, exist_ok=True)
    idx_path.write_text(
        _render_type_index(entity_type, entities), encoding="utf-8"
    )


# ═════════════════════════════════════════════════════════════════════════════
# Export engine
# ═════════════════════════════════════════════════════════════════════════════

def export_entity(entity: dict) -> pathlib.Path | None:
    """Export a single entity to its .md file.  Returns the path or None."""
    if not is_enabled():
        return None

    desc = entity.get("description", "") or ""
    md_path = _entity_md_path(entity)

    if len(desc) < _MIN_CONTENT_LENGTH:
        # Sparse entity — remove individual file if it exists (moved to index)
        if md_path.exists():
            md_path.unlink()
        # Regenerate this type's _index.md so the sparse entity appears
        # immediately rather than waiting for a full rebuild_vault().
        _refresh_type_index(entity.get("entity_type", "fact"))
        return None

    md_path.parent.mkdir(parents=True, exist_ok=True)
    content = render_entity_md(entity)
    md_path.write_text(content, encoding="utf-8")

    # Stamp the file mtime to match the entity's updated_at so that
    # check_vault_sync() only triggers when a user *actually* edits
    # the file outside Thoth — not on every export.
    try:
        ts_str = entity.get("updated_at", "")
        if ts_str:
            clean = ts_str[:19].replace("T", " ")
            dt = datetime.strptime(clean, "%Y-%m-%d %H:%M:%S")
            epoch = dt.timestamp()
            os.utime(md_path, (epoch, epoch))
    except (ValueError, OSError):
        pass  # non-critical — worst case file shows as out-of-sync

    logger.debug("Wiki export: %s", md_path)
    return md_path


def delete_entity_md(entity: dict) -> None:
    """Remove the .md file for a deleted entity."""
    if not is_enabled():
        return
    md_path = _entity_md_path(entity)
    if md_path.exists():
        md_path.unlink()
        logger.debug("Wiki deleted: %s", md_path)


def clear_wiki_folder() -> int:
    """Delete all files inside ``vault/wiki/``, preserving ``raw/`` and ``conversations/``.

    Returns the number of files removed.
    """
    vault = get_vault_path()
    wiki_dir = vault / "wiki"
    if not wiki_dir.exists():
        return 0
    removed = 0
    for item in wiki_dir.rglob("*"):
        if item.is_file():
            item.unlink()
            removed += 1
    # Remove now-empty subdirectories (bottom-up)
    for item in sorted(wiki_dir.rglob("*"), reverse=True):
        if item.is_dir() and not any(item.iterdir()):
            item.rmdir()
    logger.info("Wiki folder cleared: %d files removed", removed)
    return removed


def rebuild_vault() -> dict:
    """Full rebuild: re-export all entities and regenerate indexes.

    Removes orphan .md files that no longer match any entity.
    Returns stats dict with counts.
    """
    if not is_enabled():
        return {"error": "Wiki vault is not enabled"}

    import knowledge_graph as kg

    _ensure_vault_dirs()
    vault = get_vault_path()
    wiki_dir = vault / "wiki"

    # Snapshot existing .md files so we can remove orphans afterwards
    existing_md = {p for p in wiki_dir.rglob("*.md") if p.is_file()}

    all_entities = kg.list_entities(limit=100_000)
    exported = 0
    sparse = 0
    written_paths: set[pathlib.Path] = set()

    # Group by type for indexes
    by_type: dict[str, list[dict]] = {}
    for e in all_entities:
        etype = e.get("entity_type", "fact")
        by_type.setdefault(etype, []).append(e)

        result = export_entity(e)
        if result:
            exported += 1
            written_paths.add(result)
        else:
            sparse += 1

    # Write per-type indexes
    for etype, entities in by_type.items():
        idx_path = wiki_dir / etype / "_index.md"
        idx_path.parent.mkdir(parents=True, exist_ok=True)
        idx_path.write_text(
            _render_type_index(etype, entities), encoding="utf-8"
        )
        written_paths.add(idx_path)

    # Write master index
    master_path = wiki_dir / "index.md"
    master_path.write_text(
        _render_master_index(all_entities), encoding="utf-8"
    )
    written_paths.add(master_path)

    # Remove orphan .md files
    orphans = existing_md - written_paths
    for orphan in orphans:
        orphan.unlink()
        logger.debug("Orphan removed: %s", orphan)

    stats = {
        "total": len(all_entities),
        "exported": exported,
        "sparse": sparse,
        "types": len(by_type),
        "orphans_removed": len(orphans),
    }
    logger.info("Wiki vault rebuilt: %s", stats)
    return stats


def export_conversation(
    thread_id: str,
    messages: list[dict],
    title: str = "",
) -> pathlib.Path | None:
    """Export a conversation thread as a markdown file.

    Parameters
    ----------
    thread_id : str
        Unique identifier for the conversation.
    messages : list[dict]
        List of message dicts with 'role' and 'content' keys.
    title : str
        Optional human-readable title for the conversation.

    Returns the path to the exported file, or None if vault is disabled.
    """
    if not is_enabled():
        return None

    vault = get_vault_path()
    conv_dir = vault / "conversations"
    conv_dir.mkdir(parents=True, exist_ok=True)

    safe_title = _safe_filename(title or thread_id)
    md_path = conv_dir / f"{safe_title}.md"

    lines = [
        _AUTO_HEADER.strip(),
        f"# {title or thread_id}",
        "",
        f"Thread ID: `{thread_id}`",
        f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "",
        "---",
        "",
    ]

    for msg in messages:
        role = msg.get("role", "unknown")
        content = msg.get("content", "")
        if role in ("human", "user"):
            lines.append(f"**You:** {content}")
        elif role in ("ai", "assistant"):
            lines.append(f"**Thoth:** {content}")
        else:
            lines.append(f"**{role}:** {content}")
        lines.append("")

    md_path.write_text("\n".join(lines), encoding="utf-8")
    logger.debug("Conversation exported: %s", md_path)
    return md_path


# ═════════════════════════════════════════════════════════════════════════════
# Vault search (used by wiki_tool)
# ═════════════════════════════════════════════════════════════════════════════

def search_vault(query: str, max_results: int = 10) -> list[dict]:
    """Simple text search across all .md files in the vault.

    Returns list of dicts with 'path', 'title', 'snippet'.
    """
    if not is_enabled():
        return []

    vault = get_vault_path()
    wiki_dir = vault / "wiki"
    if not wiki_dir.exists():
        return []

    query_lower = query.lower()
    results = []

    for md_file in wiki_dir.rglob("*.md"):
        try:
            text = md_file.read_text(encoding="utf-8")
        except OSError:
            continue

        if query_lower in text.lower():
            # Extract title from first heading
            title = md_file.stem
            entity_id = ""
            for line in text.split("\n"):
                if line.startswith("# "):
                    title = line[2:].strip()
                if line.startswith("id: "):
                    entity_id = line[4:].strip()

            # Extract snippet around match
            idx = text.lower().find(query_lower)
            start = max(0, idx - 80)
            end = min(len(text), idx + len(query) + 80)
            snippet = text[start:end].replace("\n", " ").strip()

            results.append({
                "path": str(md_file.relative_to(vault)),
                "title": title,
                "snippet": snippet,
                "entity_id": entity_id,
            })

            if len(results) >= max_results:
                break

    return results


def read_article(subject: str) -> str | None:
    """Read a wiki article by entity subject name.

    Returns the full markdown content, or None if not found.
    """
    if not is_enabled():
        return None

    vault = get_vault_path()
    wiki_dir = vault / "wiki"
    safe_name = _safe_filename(subject)

    # Search across all type folders
    for md_file in wiki_dir.rglob(f"{safe_name}.md"):
        try:
            return md_file.read_text(encoding="utf-8")
        except OSError:
            continue

    return None


def get_vault_stats() -> dict:
    """Return stats about the current vault state."""
    vault = get_vault_path()
    wiki_dir = vault / "wiki"

    if not wiki_dir.exists():
        return {"articles": 0, "conversations": 0, "vault_path": str(vault)}

    articles = sum(1 for _ in wiki_dir.rglob("*.md") if _.name != "_index.md" and _.name != "index.md")
    conv_dir = vault / "conversations"
    conversations = sum(1 for _ in conv_dir.rglob("*.md")) if conv_dir.exists() else 0

    return {
        "articles": articles,
        "conversations": conversations,
        "vault_path": str(vault),
        "enabled": is_enabled(),
    }


def open_in_editor(entity: dict) -> bool:
    """Open an entity's .md file in the user's default application.

    Returns True if the file was opened, False otherwise.
    """
    md_path = _entity_md_path(entity)
    if not md_path.exists():
        return False

    import platform
    import subprocess

    try:
        system = platform.system()
        if system == "Windows":
            os.startfile(str(md_path))
        elif system == "Darwin":
            subprocess.Popen(["open", str(md_path)])
        else:
            subprocess.Popen(["xdg-open", str(md_path)])
        return True
    except Exception as exc:
        logger.warning("Failed to open %s: %s", md_path, exc)
        return False


# ═════════════════════════════════════════════════════════════════════════════
# Vault → DB sync (bidirectional)
# ═════════════════════════════════════════════════════════════════════════════

def parse_entity_md(filepath: str | pathlib.Path) -> dict | None:
    """Parse a vault ``.md`` file back into an entity dict.

    Extracts YAML frontmatter fields (id, type, subject, aliases, tags,
    source, created, updated) and the markdown body (description text
    between the ``# Subject`` heading and the ``## Connections`` section).

    Returns ``None`` if the file cannot be parsed.
    """
    filepath = pathlib.Path(filepath)
    if not filepath.exists():
        return None

    try:
        text = filepath.read_text(encoding="utf-8")
    except OSError:
        return None

    # Strip auto-header comment if present
    text = re.sub(r"<!--\s*(?:Auto-generated|Managed) by Thoth[^>]*-->\s*", "", text, count=1)

    # Parse YAML frontmatter (between --- delimiters)
    fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.DOTALL)
    if not fm_match:
        return None

    fm_text = fm_match.group(1)
    body = text[fm_match.end():]

    # Simple line-by-line YAML parsing (no pyyaml dependency)
    fm: dict[str, Any] = {}
    for line in fm_text.split("\n"):
        line = line.strip()
        if not line or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip()
        # Handle quoted strings
        if value.startswith('"') and value.endswith('"'):
            value = value[1:-1]
        # Handle list syntax [a, b, c]
        if value.startswith("[") and value.endswith("]"):
            inner = value[1:-1]
            items = []
            for item in re.findall(r"'([^']*)'|\"([^\"]*)\"|([^,]+)", inner):
                val = item[0] or item[1] or item[2].strip()
                if val:
                    items.append(val)
            value = ", ".join(items)
        if isinstance(value, str) and value and value[0] in "[{\"0123456789tfn-":
            try:
                value = json.loads(value)
            except Exception:
                pass
        fm[key] = value

    entity_id = fm.get("id", "")
    if not entity_id:
        return None

    # Extract description: text between "# Subject" and "## Connections"
    desc_match = re.search(r"^# .+?\n\s*\n(.*?)(?=\n## Connections|\Z)",
                           body, re.DOTALL)
    description = desc_match.group(1).strip() if desc_match else ""

    known = {
        "id", "type", "subject", "aliases", "tags", "source", "created", "updated",
    }
    parsed_props = {
        key: value
        for key, value in fm.items()
        if key not in known and value not in ("", None)
    }

    return {
        "id": entity_id,
        "entity_type": fm.get("type", "fact"),
        "subject": fm.get("subject", ""),
        "description": description,
        "aliases": fm.get("aliases", ""),
        "tags": fm.get("tags", ""),
        "source": fm.get("source", "live"),
        "properties": parsed_props,
        "created_at": fm.get("created", ""),
        "updated_at": fm.get("updated", ""),
    }


def check_vault_sync() -> list[dict]:
    """Compare vault ``.md`` file mtimes against DB ``updated_at`` timestamps.

    Returns a list of dicts for each out-of-sync entity::

        {"entity_id": "...", "subject": "...", "vault_path": "...",
         "vault_mtime": "2025-...", "db_updated": "2025-..."}

    An entity is out-of-sync when its vault file's mtime is strictly
    newer than its DB ``updated_at`` timestamp (meaning the user edited
    the file in Obsidian after Thoth last wrote it).
    """
    if not is_enabled():
        return []

    vault = get_vault_path()
    wiki_dir = vault / "wiki"
    if not wiki_dir.exists():
        return []

    import knowledge_graph as kg

    out_of_sync = []
    for md_file in wiki_dir.rglob("*.md"):
        if md_file.name.startswith("_") or md_file.name == "index.md":
            continue

        parsed = parse_entity_md(md_file)
        if not parsed or not parsed.get("id"):
            continue

        entity = kg.get_entity(parsed["id"])
        if not entity:
            continue

        # Compare file mtime with DB updated_at
        try:
            file_mtime = datetime.fromtimestamp(md_file.stat().st_mtime)
            db_updated_str = entity.get("updated_at", "")
            if not db_updated_str:
                continue
            # Parse DB timestamp (handles both "2025-04-10 14:30:22" and
            # ISO format "2025-04-10T14:30:22.123456")
            clean_ts = db_updated_str[:19].replace("T", " ")
            db_updated = datetime.strptime(clean_ts, "%Y-%m-%d %H:%M:%S")
            # File is newer than DB by at least 2 seconds (to avoid
            # race conditions from Thoth's own export writes)
            if file_mtime > db_updated and (file_mtime - db_updated).total_seconds() > 2:
                out_of_sync.append({
                    "entity_id": parsed["id"],
                    "subject": parsed.get("subject", entity.get("subject", "")),
                    "vault_path": str(md_file),
                    "vault_mtime": file_mtime.strftime("%Y-%m-%d %H:%M:%S"),
                    "db_updated": db_updated_str[:19],
                })
        except (OSError, ValueError):
            continue

    return out_of_sync


def import_from_vault(entity_id: str, filepath: str | pathlib.Path) -> bool:
    """Apply vault file changes to the DB for a single entity (vault wins).

    Parses the ``.md`` file and calls ``kg.update_entity()`` with the
    parsed fields.  Returns True on success, False on failure.
    """
    parsed = parse_entity_md(filepath)
    if not parsed or parsed.get("id") != entity_id:
        logger.warning("import_from_vault: parse failed or ID mismatch for %s", filepath)
        return False

    import knowledge_graph as kg
    import memory_evolution as memory_evo

    try:
        existing = kg.get_entity(entity_id)
        existing_props = existing.get("properties", {}) if existing else {}
        parsed_props = parsed.get("properties", {}) or {}
        if "status" not in parsed_props:
            parsed_props["status"] = "active"
        merged_props = memory_evo.merge_properties(
            existing_props,
            parsed_props,
            source=parsed.get("source", (existing or {}).get("source", "")),
            entity_type=parsed.get("entity_type", (existing or {}).get("entity_type", "")),
            actor="wiki",
            source_context={
                "actor": "wiki",
                "vault_path": str(filepath),
            },
            high_authority=True,
        )
        kg.update_entity(
            entity_id,
            subject=parsed.get("subject"),
            entity_type=parsed.get("entity_type"),
            description=parsed.get("description"),
            aliases=parsed.get("aliases"),
            tags=parsed.get("tags"),
            source=parsed.get("source"),
            properties=merged_props,
        )
        memory_evo.append_journal(
            "wiki_import",
            entity_id=entity_id,
            actor="wiki",
            reason="external_vault_edit",
            source=parsed.get("source", ""),
            new_status=merged_props.get("status"),
            details={"vault_path": str(filepath)},
        )
        logger.info("Imported vault changes for entity %s (%s)",
                     entity_id, parsed.get("subject"))
        return True
    except Exception as exc:
        logger.error("import_from_vault failed for %s: %s", entity_id, exc)
        return False


def sync_all_from_vault() -> dict:
    """Import all out-of-sync vault files into the DB.

    Returns ``{"synced": N, "failed": N, "details": [...]}``.
    """
    out_of_sync = check_vault_sync()
    if not out_of_sync:
        return {"synced": 0, "failed": 0, "details": []}

    synced = 0
    failed = 0
    details = []
    for item in out_of_sync:
        ok = import_from_vault(item["entity_id"], item["vault_path"])
        if ok:
            synced += 1
            details.append(f"✓ {item['subject']}")
        else:
            failed += 1
            details.append(f"✗ {item['subject']}")

    return {"synced": synced, "failed": failed, "details": details}
