import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/index', 'getting-started/installation', 'getting-started/first-launch'],
    },
    {
      type: 'category',
      label: 'App Shell',
      collapsed: false,
      items: ['app-shell/navigation'],
    },
    {
      type: 'category',
      label: 'Chat',
      collapsed: false,
      items: ['chat/index', 'chat/model-picker', 'chat/tools-approvals-and-terminal'],
    },
    {
      type: 'category',
      label: 'Home',
      collapsed: false,
      items: ['home/workflows', 'home/designer', 'home/developer', 'home/knowledge', 'home/monitor'],
    },
    'designer/index',
    'developer/index',
    {
      type: 'category',
      label: 'Settings',
      collapsed: false,
      items: [
        'settings/index',
        'settings/providers',
        'settings/models',
        'settings/documents',
        'settings/search',
        'settings/skills',
        'settings/system',
        'settings/accounts',
        'settings/utilities',
        'settings/tracker',
        'settings/knowledge',
        'settings/buddy',
        'settings/voice',
        'settings/channels',
        'settings/mcp',
        'settings/plugins',
        'settings/preferences',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: ['integrations/channels', 'integrations/mcp', 'integrations/plugins', 'skills/index', 'voice-and-buddy/index'],
    },
    'privacy-safety/index',
    'troubleshooting/index',
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/index',
        {
          type: 'category',
          label: 'Generated',
          collapsed: false,
          items: [
            'reference/generated/index',
            'reference/generated/tools',
            'reference/generated/providers',
            'reference/generated/settings',
            'reference/generated/home-tabs',
            'reference/generated/channels',
            'reference/generated/skills',
            'reference/generated/mcp',
            'reference/generated/plugins',
            'reference/generated/data-storage',
            'reference/generated/safety-approvals',
            'reference/generated/environment-and-config',
            'reference/generated/screenshots',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
