import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/index',
        'getting-started/installation',
        'getting-started/first-launch',
        'configuration/models-and-providers',
      ],
    },
    {
      type: 'category',
      label: 'Use Row-Bot',
      collapsed: false,
      items: [
        'app-shell/navigation',
        'chat/index',
        'chat/model-picker',
        'chat/tools-approvals-and-terminal',
        'profiles-goals-agents/index',
        'guides/workflows',
        'designer/index',
        'developer/index',
        'knowledge/index',
        'knowledge/wiki-vault',
        'knowledge/provenance-repair',
        'monitor/index',
        'mobile-native/index',
      ],
    },
    {
      type: 'category',
      label: 'How Row-Bot Works',
      collapsed: false,
      items: [
        'concepts/index',
        'concepts/request-lifecycle',
        'concepts/memory-knowledge-and-dream-cycle',
        'concepts/profiles-goals-and-agents',
        'concepts/background-workflows',
        'concepts/extensions-and-trust',
      ],
    },
    {
      type: 'category',
      label: 'Settings',
      collapsed: false,
      items: [
        'settings/index',
        'settings/providers',
        'settings/models',
        'settings/knowledge',
        'settings/buddy',
        'settings/voice',
        'settings/system',
        'settings/tracker',
        'settings/documents',
        'settings/search',
        'settings/skills',
        'settings/accounts',
        'settings/channels',
        'settings/utilities',
        'settings/mcp',
        'settings/plugins',
        'settings/preferences',
      ],
    },
    {
      type: 'category',
      label: 'Connect And Extend',
      collapsed: false,
      items: [
        'extending/index',
        'integrations/accounts',
        'integrations/channels',
        'skills/index',
        'integrations/plugins',
        'integrations/mcp',
        'voice-and-buddy/index',
      ],
    },
    {
      type: 'category',
      label: 'Operations And Safety',
      collapsed: false,
      items: ['operations/index', 'privacy-safety/index', 'troubleshooting/index'],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        'reference/index',
        'reference/generated/tools',
        'reference/generated/providers',
        'reference/generated/settings',
        'reference/generated/settings-controls',
        'reference/generated/home-tabs',
        'reference/generated/channels',
        'reference/generated/skills',
        'reference/generated/mcp',
        'reference/generated/plugins',
        'reference/generated/data-storage',
        'reference/generated/safety-approvals',
        'reference/generated/environment-and-config',
        'reference/generated/cli',
        'reference/generated/screenshots',
      ],
    },
  ],
};

export default sidebars;
