"""The one-time tidy back to readable article names (B256), on synthetic vaults.

v4.9.1 wrote ``wiki/<type>/<Subject>.md`` without an ownership manifest; later
builds wrote ``wiki/<type>/entity-<sha256>.md`` with one and left the old files
beside them. The tidy adopts the app's own old articles in place, gives every
memory one readable article, moves the hashed copies to
``raw/.row-bot-retired/hashed-names-<date>/`` and never deletes or touches
files the app doesn't own.
"""
from __future__ import annotations

import hashlib
import json
import os
import sqlite3
import sys
import time
from contextlib import closing
from datetime import datetime
from pathlib import Path

import pytest

pytestmark = [pytest.mark.integration, pytest.mark.subsystem, pytest.mark.platform]

HEADER = "<!-- Auto-generated by Row-Bot — edits here sync back to the knowledge graph -->\n\n"


def _saved_time(entity: dict) -> float:
    return datetime.fromisoformat(entity["updated_at"][:19]).timestamp()


def _v491_article(stack, entity: dict, *, description: str | None = None, header: str = HEADER) -> Path:
    """An article as v4.9.1 wrote it: named after the subject, stamped with the save time."""
    front = ["---", f'id: "{entity["id"]}"', f"type: {entity['entity_type']}", f'subject: "{entity["subject"]}"']
    if entity.get("aliases"):
        front.append("aliases: [" + ", ".join(repr(alias.strip()) for alias in entity["aliases"].split(",")) + "]")
    front += [f"source: {entity['source']}", f"created: {entity['created_at']}", f"updated: {entity['updated_at']}", "---"]
    body = entity["description"] if description is None else description
    path = stack["vault"] / "wiki" / entity["entity_type"] / f"{entity['subject']}.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(header + "\n".join(front) + f"\n\n# {entity['subject']}\n\n{body}\n\n", encoding="utf-8")
    os.utime(path, (_saved_time(entity), _saved_time(entity)))
    return path


def _manifest_file(stack) -> Path:
    return stack["vault"] / "wiki" / ".row-bot-ownership.json"


def _own(stack, relative: str, data: bytes, entity: dict | None = None) -> Path:
    """A file the hashed-name builds published and recorded in the ownership manifest."""
    path = stack["vault"] / "wiki" / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)
    manifest_path = _manifest_file(stack)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8")) if manifest_path.exists() else {"version": 1, "files": {}}
    entry = {"hash": hashlib.sha256(data).hexdigest()}
    if entity is not None:
        entry.update(entity_id=entity["id"], subject=entity["subject"],
                     source_revision=stack["wiki_vault"]._source_revision(entity),
                     source_updated_at=entity["updated_at"])
    manifest["files"][relative] = entry
    manifest_path.write_text(json.dumps(manifest), encoding="utf-8")
    return path


def _hashed_name(entity: dict) -> str:
    return f"entity-{hashlib.sha256(entity['id'].encode()).hexdigest()}"


def _hashed_article(stack, entity: dict) -> Path:
    content = stack["wiki_vault"].render_entity_md(entity).replace("\n", "\r\n")
    return _own(stack, f"{entity['entity_type']}/{_hashed_name(entity)}.md", content.encode("utf-8"), entity)


def _tree(root: Path) -> dict[str, bytes]:
    return {path.relative_to(root).as_posix(): path.read_bytes() for path in root.rglob("*") if path.is_file()}


def _memory(stack, subject: str, description: str | None = None, entity_type: str = "person", **fields) -> dict:
    return stack["kg"].save_entity(entity_type, subject, description or f"{subject} has enough synthetic detail.",
                                   source="test", **fields)


@pytest.fixture
def stack(wiki_stack):
    wiki_stack["wiki_vault"].set_enabled(True)
    return wiki_stack


def test_v491_vault_is_adopted_in_place_byte_identical(stack):
    wiki, vault = stack["wiki_vault"], stack["vault"]
    alice = _memory(stack, "Alice")
    bob = _memory(stack, "Bob", aliases="Bobby, Robert")
    thoth = _memory(stack, "Tess")  # untouched since the app was called Thoth
    restored = _memory(stack, "Rhea")  # copied back from a backup: a new time, the same content
    _memory(stack, "Tiny", "Short")
    _v491_article(stack, alice)
    _v491_article(stack, bob)
    _v491_article(stack, thoth, header=HEADER.replace("Row-Bot", "Thoth"))
    later = time.time() + 3600
    os.utime(_v491_article(stack, restored), (later, later))
    (vault / "wiki" / "person" / "_index.md").write_text(HEADER + "# Person\n\n- [[Alice]]\n- [[Bob]]\n", encoding="utf-8")
    (vault / "wiki" / "index.md").write_text(HEADER + "# Row-Bot Knowledge Base\n", encoding="utf-8")
    note = vault / "wiki" / "person" / "Notes.md"
    note.write_text("My own note about Alice.", encoding="utf-8")
    before = _tree(vault)

    report = wiki.tidy_vault()

    assert {name: data for name, data in _tree(vault).items() if name != "wiki/.row-bot-ownership.json"} == before
    assert not (vault / "raw" / ".row-bot-retired").exists()
    assert report["adopted"] == 6 and report["tidied"] == 0 and report["moved"] == [] and report["review"] == []
    assert wiki.check_vault_sync() == []
    # Adopted articles keep their names: the next save refreshes them in place.
    for entity in (alice, bob, thoth, restored):
        path = wiki.export_entity(stack["kg"].get_entity(entity["id"]))
        assert path == vault / "wiki" / "person" / f"{entity['subject']}.md"
    assert note.read_text(encoding="utf-8") == "My own note about Alice."


def test_mixed_vault_keeps_one_readable_article_per_memory_and_moves_hashed_copies(stack):
    wiki, kg, vault = stack["wiki_vault"], stack["kg"], stack["vault"]
    alice = _memory(stack, "Alice", "An older description of Alice.")
    legacy = _v491_article(stack, alice)
    os.utime(legacy, (_saved_time(alice) - 60, _saved_time(alice) - 60))  # written before the latest change
    alice = kg.update_entity(alice["id"], "Alice keeps a zebracorn in the garden shed, now indoors.")
    bob = _memory(stack, "Bob")  # saved after the switch to hashed names: no old article
    device = _memory(stack, "NUL", "A memory whose subject is a Windows device name.")
    kg.add_relation(alice["id"], bob["id"], "friend_of", source="test")
    alice = kg.get_entity(alice["id"])
    hashed = {entity["id"]: _hashed_article(stack, entity) for entity in (alice, bob, device)}
    rollup = _own(stack, "person/_index.md", (HEADER + f"# Person\n\n- [[{_hashed_name(alice)}|Alice]]\n").encode())
    before = {name: data for name, data in _tree(vault).items() if name != "wiki/.row-bot-ownership.json"}

    report = wiki.tidy_vault()

    person = sorted(path.name for path in (vault / "wiki" / "person").glob("*.md"))
    assert person == ["Alice.md", "Bob.md", "_NUL.md", "_index.md"]
    article = (vault / "wiki" / "person" / "Alice.md").read_text(encoding="utf-8")
    assert "now indoors" in article and "[[Bob]]" in article
    assert "entity-" not in rollup.read_text(encoding="utf-8")
    assert report["tidied"] == 3 and len(report["moved"]) == 3
    retired = vault / report["folder"] / "person"
    for entity_id, path in hashed.items():
        assert not path.exists()
        assert (retired / path.name).read_bytes() == before[path.relative_to(vault).as_posix()]
    # Nothing is deleted: every earlier version is still in the vault.
    after = set(_tree(vault).values())
    assert all(data in after for data in before.values())
    assert wiki.get_vault_stats()["articles"] == 3
    assert [hit["entity_id"] for hit in wiki.search_vault("zebracorn")] == [alice["id"]]
    assert wiki.check_vault_sync() == []


def test_an_old_article_the_manifest_lists_as_imported_is_adopted_not_duplicated(stack):
    # A memory imported from its own old article (wiki sync-back) left that file in
    # the manifest as not managed; the tidy must still adopt it, not add a copy.
    wiki, kg, vault = stack["wiki_vault"], stack["kg"], stack["vault"]
    memory = _memory(stack, "64K context window", entity_type="concept")
    legacy = _v491_article(stack, memory)
    os.utime(legacy, (_saved_time(memory) - 60, _saved_time(memory) - 60))
    memory = kg.update_entity(memory["id"], "A 64K context window holds about fifty pages of text.")
    _hashed_article(stack, memory)
    manifest = json.loads(_manifest_file(stack).read_text(encoding="utf-8"))
    manifest["files"]["concept/64K context window.md"] = {
        "hash": hashlib.sha256(legacy.read_bytes()).hexdigest(), "entity_id": memory["id"], "managed": False}
    _manifest_file(stack).write_text(json.dumps(manifest), encoding="utf-8")

    report = wiki.tidy_vault()

    assert sorted(path.name for path in (vault / "wiki" / "concept").glob("*.md")) == ["64K context window.md"]
    assert "fifty pages" in legacy.read_text(encoding="utf-8")
    assert report["tidied"] == 1 and report["review"] == []


def test_clash_with_a_users_own_note_adds_a_short_id_and_leaves_the_note(stack):
    wiki, vault = stack["wiki_vault"], stack["vault"]
    dana = _memory(stack, "Dana")
    note = vault / "wiki" / "person" / "Dana.md"
    note.parent.mkdir(parents=True, exist_ok=True)
    note.write_text("# Dana\n\nMy own note, not the app's.\n", encoding="utf-8")
    _hashed_article(stack, dana)

    wiki.tidy_vault()

    articles = sorted(path.name for path in note.parent.glob("Dana*.md"))
    assert articles == ["Dana (" + hashlib.sha256(dana["id"].encode()).hexdigest()[:6] + ").md", "Dana.md"]
    assert note.read_text(encoding="utf-8") == "# Dana\n\nMy own note, not the app's.\n"


def test_hand_edited_old_article_stays_and_is_listed_for_review(stack):
    wiki = stack["wiki_vault"]
    erin = _memory(stack, "Erin")
    edited = _v491_article(stack, erin)
    edited.write_text(edited.read_text(encoding="utf-8") + "A line I added in Obsidian.\n", encoding="utf-8")
    later = time.time() + 3600
    os.utime(edited, (later, later))
    kept = edited.read_bytes()
    _hashed_article(stack, erin)

    report = wiki.tidy_vault()

    assert edited.read_bytes() == kept
    assert {"relative": "wiki/person/Erin.md", "reason": "edited"} in report["review"]
    assert any(item["status"] in {"legacy_review", "conflict"} and item["vault_path"] == str(edited)
               for item in wiki.check_vault_sync())
    names = sorted(path.name for path in edited.parent.glob("Erin*.md"))
    assert len(names) == 2 and names[1] == "Erin.md" and names[0].startswith("Erin (")
    assert len(report["moved"]) == 1


def test_second_run_and_later_writes_change_nothing_more(stack):
    wiki, kg, vault = stack["wiki_vault"], stack["kg"], stack["vault"]
    fern = _memory(stack, "Fern")
    _v491_article(stack, fern)
    _hashed_article(stack, fern)
    report = wiki.tidy_vault()
    tidied = _tree(vault)

    assert wiki.tidy_vault() == report
    assert _tree(vault) == tidied
    late = _v491_article(stack, _memory(stack, "Gale"))  # an old-style article copied in afterwards
    wiki.export_entity(kg.get_entity(fern["id"]))  # a later write does not tidy again
    wiki.clear_wiki_folder()
    assert late.exists() and not (vault / "wiki" / "person" / "Fern.md").exists()


def test_dry_run_reports_the_tidy_and_writes_nothing(stack):
    wiki, kg, vault = stack["wiki_vault"], stack["kg"], stack["vault"]
    hana = _memory(stack, "Hana")
    ivo = _memory(stack, "Ivo")
    _v491_article(stack, hana)
    _hashed_article(stack, hana)
    _hashed_article(stack, ivo)
    before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in vault.rglob("*") if path.is_file()}
    with closing(sqlite3.connect(kg.DB_PATH)) as conn:
        saved = conn.execute("SELECT * FROM entities ORDER BY id").fetchall()

    plan = wiki.plan_vault_tidy()

    assert {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in vault.rglob("*") if path.is_file()} == before
    with closing(sqlite3.connect(kg.DB_PATH)) as conn:
        assert conn.execute("SELECT * FROM entities ORDER BY id").fetchall() == saved
    assert plan["needed"] is True
    assert plan["adopt"] == ["person/Hana.md"]
    assert plan["refresh"] == ["person/Hana.md"] and plan["create"] == ["person/Ivo.md"]
    assert sorted(move["from"] for move in plan["move"]) == sorted(
        f"wiki/person/{_hashed_name(entity)}.md" for entity in (hana, ivo))
    report = wiki.tidy_vault()
    assert sorted(report["moved"], key=str) == sorted(plan["move"], key=str)
    assert wiki.plan_vault_tidy()["needed"] is False


def test_renamed_memory_refreshes_the_articles_linking_to_it(stack):
    wiki, kg = stack["wiki_vault"], stack["kg"]
    jo = _memory(stack, "Jo")
    kim = _memory(stack, "Kim")
    kg.add_relation(jo["id"], kim["id"], "friend_of", source="test")
    wiki.export_entity(kg.get_entity(jo["id"]))
    wiki.export_entity(kg.get_entity(kim["id"]))

    def queued_for_jo():
        with closing(sqlite3.connect(kg.DB_PATH)) as conn:
            return conn.execute("SELECT revision,wiki_pending FROM knowledge_projection_work WHERE entity_id=?",
                                (jo["id"],)).fetchone()

    before = queued_for_jo()
    renamed = kg.update_entity(kim["id"], kim["description"], subject="Kimberly")
    assert wiki.export_entity(renamed).name == "Kimberly.md"
    revision, pending = queued_for_jo()
    assert revision > before[0] and pending == 1
    article = wiki.export_entity(kg.get_entity(jo["id"]))
    assert "[[Kimberly]]" in article.read_text(encoding="utf-8")


def _link_directory(link: Path, target: Path) -> None:
    try:
        link.symlink_to(target, target_is_directory=True)
    except OSError:
        if sys.platform != "win32":
            pytest.skip("symlinks are not available")
        import _winapi

        _winapi.CreateJunction(str(target), str(link))


def test_moves_never_follow_a_linked_retired_folder(stack, tmp_path):
    wiki, vault = stack["wiki_vault"], stack["vault"]
    lena = _memory(stack, "Lena")
    hashed = _hashed_article(stack, lena)
    outside = tmp_path / "outside"
    outside.mkdir()
    (vault / "raw").mkdir(parents=True, exist_ok=True)
    _link_directory(vault / "raw" / ".row-bot-retired", outside)

    report = wiki.tidy_vault()

    assert list(outside.iterdir()) == []
    assert hashed.exists()
    assert {"relative": f"wiki/person/{hashed.name}", "reason": "not_moved"} in report["review"]
    assert (vault / "wiki" / "person" / "Lena.md").exists()
