from __future__ import annotations

# Generated migration ledger for the retired legacy monoliths.
# Keep this snapshot stable so coverage proof survives after the old files shrink.

LEGACY_INVENTORY_SNAPSHOT = ({'legacy_file': 'tests/test_suite.py',
  'heading': '1. AST SYNTAX CHECK',
  'start_line': 197,
  'end_line': 218,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '2. CORE MODULE IMPORTS',
  'start_line': 219,
  'end_line': 284,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '3. TOOL MODULE IMPORTS',
  'start_line': 285,
  'end_line': 323,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '4. CHANNEL MODULE IMPORTS',
  'start_line': 324,
  'end_line': 348,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '5. KEY FUNCTION / CLASS EXISTENCE',
  'start_line': 349,
  'end_line': 435,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '6. TOOL REGISTRY CHECK',
  'start_line': 436,
  'end_line': 473,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '7. LAUNCHER SPLASH SCREEN VALIDATION',
  'start_line': 474,
  'end_line': 512,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '8. CHANNELS CONFIG ROUND-TRIP',
  'start_line': 513,
  'end_line': 536,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '9. THREAD DB CONNECTIVITY',
  'start_line': 537,
  'end_line': 550,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '10. NO STREAMLIT IMPORTS IN app.py',
  'start_line': 551,
  'end_line': 579,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '11. NiceGUI APP AST PARSE + BASIC IMPORT CHECK',
  'start_line': 580,
  'end_line': 600,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '12. KEY DEPENDENCY CHECKS',
  'start_line': 601,
  'end_line': 628,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '13. TRACKER TOOL FUNCTIONAL TESTS',
  'start_line': 629,
  'end_line': 927,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '14. LIVE LAUNCH TEST (port 8080)',
  'start_line': 928,
  'end_line': 953,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '15. CROSS-PLATFORM LOGIC TESTS',
  'start_line': 954,
  'end_line': 1156,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '16. PROMPT CONTENT VALIDATION',
  'start_line': 1157,
  'end_line': 1606,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '18. SHELL TOOL',
  'start_line': 1607,
  'end_line': 1757,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '19. BROWSER TOOL',
  'start_line': 1758,
  'end_line': 1962,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '20. BROWSER SNAPSHOT COMPRESSION',
  'start_line': 1963,
  'end_line': 2145,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '21. TASK TOOL',
  'start_line': 2146,
  'end_line': 2256,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '22. ACTIVITY TAB helpers',
  'start_line': 2257,
  'end_line': 2369,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '23. CHANNEL DELIVERY fixes',
  'start_line': 2370,
  'end_line': 2585,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '── 24. Task Engine Comprehensive Tests ──',
  'start_line': 2586,
  'end_line': 3010,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '26. KNOWLEDGE GRAPH',
  'start_line': 3011,
  'end_line': 3288,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 27 · Knowledge Graph Visualization',
  'start_line': 3289,
  'end_line': 3491,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 28 · Triple-based Extraction',
  'start_line': 3492,
  'end_line': 3625,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '29. TELEGRAM TOOL',
  'start_line': 3626,
  'end_line': 3746,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '30. FILE & MESSAGING PIPELINE (v3.6.0)',
  'start_line': 3747,
  'end_line': 4553,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '33. TOOL DEFAULT CONFIGURATION',
  'start_line': 4554,
  'end_line': 4640,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '34. EXPORT FILENAME SANITIZATION',
  'start_line': 4641,
  'end_line': 4710,
  'subsystem': 'designer',
  'replacement_paths': ('tests/subsystem/designer',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/designer -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '35. CLOUD MODEL SUPPORT — DYNAMIC + CLOUD-PRIMARY (v3.7.0)',
  'start_line': 4711,
  'end_line': 5474,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '36. SKILLS ENGINE',
  'start_line': 5475,
  'end_line': 6237,
  'subsystem': 'skills',
  'replacement_paths': ('tests/test_skills_activation.py',
                        'tests/test_skills_hub.py',
                        'tests/test_skills_hub_search.py',
                        'tests/test_skills_hub_sources.py',
                        'tests/test_skill_pinning.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_skills_activation.py tests/test_skills_hub.py '
                          'tests/test_skills_hub_search.py tests/test_skills_hub_sources.py '
                          'tests/test_skill_pinning.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '37. SMOKE REGRESSION',
  'start_line': 6238,
  'end_line': 6354,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '38. IMAGE HANDLING IMPROVEMENTS',
  'start_line': 6355,
  'end_line': 6541,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '39. OAUTH TOKEN HEALTH CHECK',
  'start_line': 6542,
  'end_line': 6617,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '40. ARXIV TOOL REWRITE',
  'start_line': 6618,
  'end_line': 6720,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '41. Status Monitor',
  'start_line': 6721,
  'end_line': 7004,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '42. WIKI VAULT',
  'start_line': 7005,
  'end_line': 7181,
  'subsystem': 'wiki_vault',
  'replacement_paths': ('tests/integration/wiki_vault', 'tests/subsystem/knowledge_graph'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/integration/wiki_vault tests/subsystem/knowledge_graph -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '43. AUTO-RECALL IMPROVEMENTS',
  'start_line': 7182,
  'end_line': 7241,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '44. WIKI TOOL',
  'start_line': 7242,
  'end_line': 7278,
  'subsystem': 'wiki_vault',
  'replacement_paths': ('tests/integration/wiki_vault', 'tests/subsystem/knowledge_graph'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/integration/wiki_vault tests/subsystem/knowledge_graph -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '45. BUNDLED SKILLS UPDATED',
  'start_line': 7279,
  'end_line': 7350,
  'subsystem': 'skills',
  'replacement_paths': ('tests/test_skills_activation.py',
                        'tests/test_skills_hub.py',
                        'tests/test_skills_hub_search.py',
                        'tests/test_skills_hub_sources.py',
                        'tests/test_skill_pinning.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_skills_activation.py tests/test_skills_hub.py '
                          'tests/test_skills_hub_search.py tests/test_skills_hub_sources.py '
                          'tests/test_skill_pinning.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '46. DOCUMENT KNOWLEDGE EXTRACTION (MAP-REDUCE)',
  'start_line': 7351,
  'end_line': 7560,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '47. WIKI CLEANUP & KNOWLEDGE TAB CONSOLIDATION',
  'start_line': 7561,
  'end_line': 7678,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '48. DREAM CYCLE',
  'start_line': 7679,
  'end_line': 8127,
  'subsystem': 'dream_cycle',
  'replacement_paths': ('tests/subsystem/dream_cycle',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/dream_cycle -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '49. PLUGIN SYSTEM',
  'start_line': 8128,
  'end_line': 8495,
  'subsystem': 'plugins',
  'replacement_paths': ('tests/contracts/plugins', 'tests/subsystem/plugins'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/plugins tests/subsystem/plugins -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '50. PLUGIN SETTINGS UI',
  'start_line': 8496,
  'end_line': 8591,
  'subsystem': 'plugins',
  'replacement_paths': ('tests/contracts/plugins', 'tests/subsystem/plugins'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/plugins tests/subsystem/plugins -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '51. PLUGIN MARKETPLACE & INSTALLER',
  'start_line': 8592,
  'end_line': 8831,
  'subsystem': 'plugins',
  'replacement_paths': ('tests/contracts/plugins', 'tests/subsystem/plugins'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/plugins tests/subsystem/plugins -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '52. IMAGE GENERATION TOOL',
  'start_line': 8832,
  'end_line': 9385,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '52½. VIDEO GENERATION TOOL',
  'start_line': 9386,
  'end_line': 9582,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '53. PLUGIN API v2 — RICH RETURNS & DESTRUCTIVE ACTIONS',
  'start_line': 9583,
  'end_line': 9777,
  'subsystem': 'plugins',
  'replacement_paths': ('tests/contracts/plugins', 'tests/subsystem/plugins'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/plugins tests/subsystem/plugins -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 54 · Google Account Unified Setup',
  'start_line': 9778,
  'end_line': 9870,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 55 · Channel Infrastructure',
  'start_line': 9871,
  'end_line': 10068,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 56 · Telegram Phase 1 – Inbound Media & Reactions',
  'start_line': 10069,
  'end_line': 10457,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'AUDIT FIX TESTS',
  'start_line': 10458,
  'end_line': 10716,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'CONDITION OPERATOR TESTS',
  'start_line': 10717,
  'end_line': 11234,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '56. MEMORY SYSTEM BUG FIXES',
  'start_line': 11235,
  'end_line': 11607,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '── Section 50: Prompt‑Injection Defence ──',
  'start_line': 11608,
  'end_line': 11804,
  'subsystem': 'security',
  'replacement_paths': ('tests/test_approval_policy.py',
                        'tests/test_agent_approvals.py',
                        'tests/test_agent_write_locks.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_approval_policy.py tests/test_agent_approvals.py '
                          'tests/test_agent_write_locks.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '── Section 51: Persistent Logging ──',
  'start_line': 11805,
  'end_line': 12010,
  'subsystem': 'logging',
  'replacement_paths': ('tests/subsystem/logging/test_persistent_logging.py',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/logging -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '52. ANTHROPIC + GOOGLE CLOUD PROVIDERS (v3.14.0)',
  'start_line': 12011,
  'end_line': 12425,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 57 · Dream Cycle Tuning — Quality Fixes',
  'start_line': 12426,
  'end_line': 12585,
  'subsystem': 'dream_cycle',
  'replacement_paths': ('tests/subsystem/dream_cycle',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/dream_cycle -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '58. KNOWLEDGE EDITABILITY, VAULT SYNC & HYBRID SEARCH',
  'start_line': 12586,
  'end_line': 12795,
  'subsystem': 'wiki_vault',
  'replacement_paths': ('tests/integration/wiki_vault', 'tests/subsystem/knowledge_graph'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/integration/wiki_vault tests/subsystem/knowledge_graph -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '59. INTERACTIVE TERMINAL',
  'start_line': 12796,
  'end_line': 12980,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'THREAD LIFECYCLE & TASK CONSISTENCY TESTS (60)',
  'start_line': 12981,
  'end_line': 13175,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '65. X (TWITTER) TOOL',
  'start_line': 13176,
  'end_line': 13512,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '66. STREAMING FINISH-REASON DETECTION',
  'start_line': 13513,
  'end_line': 13816,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 67 · Tunnel & Webhook Infrastructure',
  'start_line': 13817,
  'end_line': 13990,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '68. VERSION SMOKE TEST',
  'start_line': 13991,
  'end_line': 14363,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '69. CODEBASE CONSISTENCY CHECKS',
  'start_line': 14364,
  'end_line': 14906,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '70. Context Management Revamp',
  'start_line': 14907,
  'end_line': 15061,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '71. Context Management Revamp — E2E pipeline tests',
  'start_line': 15062,
  'end_line': 15395,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': '72. DESIGNER STUDIO',
  'start_line': 15396,
  'end_line': 19454,
  'subsystem': 'designer',
  'replacement_paths': ('tests/subsystem/designer',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/designer -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 73: Auto-Update',
  'start_line': 19455,
  'end_line': 19725,
  'subsystem': 'updater',
  'replacement_paths': ('tests/subsystem/updater/test_updater_contracts.py',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/updater -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 74: Tool Schema Gemini Compatibility',
  'start_line': 19726,
  'end_line': 19874,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 75: MiniMax Provider',
  'start_line': 19875,
  'end_line': 19944,
  'subsystem': 'providers',
  'replacement_paths': ('tests/contracts/test_provider_contract.py',
                        'tests/subsystem/providers',
                        'tests/test_provider_runtime.py',
                        'tests/test_streaming_batcher.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_provider_contract.py tests/subsystem/providers '
                          'tests/test_provider_runtime.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_suite.py',
  'heading': 'SECTION 76: Developer Studio Foundations',
  'start_line': 19945,
  'end_line': 20232,
  'subsystem': 'developer_studio',
  'replacement_paths': ('tests/subsystem/developer', 'tests/test_developer_studio_phase2.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/developer tests/test_developer_studio_phase2.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 1 · Prerequisites',
  'start_line': 117,
  'end_line': 169,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 2 · Agent basic capabilities (LLM-dependent)',
  'start_line': 170,
  'end_line': 294,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 3 · Memory & Knowledge Graph operations',
  'start_line': 295,
  'end_line': 488,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 4 · Memory extraction pipeline (LLM-dependent)',
  'start_line': 489,
  'end_line': 620,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 5 · Agent memory recall pipeline (LLM-dependent)',
  'start_line': 621,
  'end_line': 703,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 6 · Tool functions (direct invocation, no agent)',
  'start_line': 704,
  'end_line': 803,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 7 · Task engine',
  'start_line': 804,
  'end_line': 928,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 8 · TTS (Text-to-Speech)',
  'start_line': 929,
  'end_line': 1002,
  'subsystem': 'voice',
  'replacement_paths': ('tests/test_voice_actions.py',
                        'tests/test_voice_agent_bridge.py',
                        'tests/test_voice_coordinator.py',
                        'tests/test_voice_runtime.py',
                        'tests/test_voice_speech_policy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_voice_actions.py tests/test_voice_agent_bridge.py '
                          'tests/test_voice_coordinator.py tests/test_voice_runtime.py '
                          'tests/test_voice_speech_policy.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 9 · Agent tool routing (LLM-dependent)',
  'start_line': 1003,
  'end_line': 1114,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 10 · End-to-end agent + extraction flow (LLM-dependent)',
  'start_line': 1115,
  'end_line': 1216,
  'subsystem': 'agents',
  'replacement_paths': ('tests/test_agent_context.py',
                        'tests/test_agent_runner.py',
                        'tests/test_agent_runs.py',
                        'tests/test_agent_profiles.py',
                        'tests/test_goal_mode.py',
                        'tests/test_row_bot_status_agents.py',
                        'tests/test_home_status_workflow_buddy.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_context.py tests/test_agent_runner.py '
                          'tests/test_agent_runs.py tests/test_agent_profiles.py tests/test_goal_mode.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 11 · Data integrity & edge cases',
  'start_line': 1217,
  'end_line': 1342,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 12 · Tool sub-tools (direct invocation, extended)',
  'start_line': 1343,
  'end_line': 1678,
  'subsystem': 'tools',
  'replacement_paths': ('tests/test_agent_tool.py',
                        'tests/test_agent_tool_catalog.py',
                        'tests/test_tool_config_isolation.py',
                        'tests/test_wikipedia_tool.py',
                        'tests/test_row_bot_tool_ids.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_agent_tool.py tests/test_agent_tool_catalog.py '
                          'tests/test_tool_config_isolation.py tests/test_wikipedia_tool.py '
                          'tests/test_row_bot_tool_ids.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 13 · Channel utilities (pure functions)',
  'start_line': 1679,
  'end_line': 1790,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 14 · Background task permissions & ContextVars',
  'start_line': 1791,
  'end_line': 1919,
  'subsystem': 'workflows',
  'replacement_paths': ('tests/subsystem/workflows', 'tests/test_workflow_delivery_defaults.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/workflows tests/test_workflow_delivery_defaults.py '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 15 · Bug-fix verifications',
  'start_line': 1920,
  'end_line': 2065,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 16 · Skills Engine',
  'start_line': 2066,
  'end_line': 2364,
  'subsystem': 'skills',
  'replacement_paths': ('tests/test_skills_activation.py',
                        'tests/test_skills_hub.py',
                        'tests/test_skills_hub_search.py',
                        'tests/test_skills_hub_sources.py',
                        'tests/test_skill_pinning.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/test_skills_activation.py tests/test_skills_hub.py '
                          'tests/test_skills_hub_search.py tests/test_skills_hub_sources.py '
                          'tests/test_skill_pinning.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 17 · Wiki Vault integration',
  'start_line': 2365,
  'end_line': 2535,
  'subsystem': 'wiki_vault',
  'replacement_paths': ('tests/integration/wiki_vault', 'tests/subsystem/knowledge_graph'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/integration/wiki_vault tests/subsystem/knowledge_graph -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 18 · Document Knowledge Extraction Pipeline',
  'start_line': 2536,
  'end_line': 2707,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 19 · v3.14.0 — Editability, Vault Sync & Hybrid Search (live DB)',
  'start_line': 2708,
  'end_line': 2935,
  'subsystem': 'wiki_vault',
  'replacement_paths': ('tests/integration/wiki_vault', 'tests/subsystem/knowledge_graph'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/integration/wiki_vault tests/subsystem/knowledge_graph -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/integration_tests.py',
  'heading': 'SECTION 20 · Channel Infrastructure Integration',
  'start_line': 2936,
  'end_line': 3376,
  'subsystem': 'channels',
  'replacement_paths': ('tests/contracts/test_channel_contract.py',
                        'tests/subsystem/channels',
                        'tests/test_tunnel_manager.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/contracts/test_channel_contract.py tests/subsystem/channels '
                          '-q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 1 · Prerequisites & Connectivity',
  'start_line': 114,
  'end_line': 198,
  'subsystem': 'app_startup',
  'replacement_paths': ('tests/test_dependency_metadata.py',
                        'tests/test_optional_dependency_imports.py',
                        'tests/test_startup_hardening.py',
                        'tests/test_app_port.py',
                        'tests/subsystem/installer'),
  'status': 'covered',
  'verification_command': 'uv run python scripts/run_test_matrix.py fast',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 2 · Entity CRUD (full lifecycle)',
  'start_line': 199,
  'end_line': 387,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 3 · Semantic Search & FAISS',
  'start_line': 388,
  'end_line': 523,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 4 · Graph Structure & Traversal',
  'start_line': 524,
  'end_line': 660,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 5 · LLM Memory Extraction (quality assessment)',
  'start_line': 661,
  'end_line': 810,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 6 · Dedup & Save Pipeline',
  'start_line': 811,
  'end_line': 949,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 7 · Dream Cycle (merge, enrich, infer)',
  'start_line': 950,
  'end_line': 1107,
  'subsystem': 'dream_cycle',
  'replacement_paths': ('tests/subsystem/dream_cycle',),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/dream_cycle -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 8 · Full Extraction Pipeline (run_extraction flow)',
  'start_line': 1108,
  'end_line': 1286,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 9 · Graph Integrity & Thread Safety',
  'start_line': 1287,
  'end_line': 1415,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 10 · Edge Cases & Robustness',
  'start_line': 1416,
  'end_line': 1555,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 11 · LLM Extraction Stress Tests',
  'start_line': 1556,
  'end_line': 1700,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 12 · Repair & Maintenance Operations',
  'start_line': 1701,
  'end_line': 1750,
  'subsystem': 'legacy_regression',
  'replacement_paths': ('tests/subsystem/regression', 'tests/integration/wiki_vault'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/regression tests/integration/wiki_vault -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 13 · Document Loading & Chunking',
  'start_line': 1751,
  'end_line': 1917,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 14 · Document Extraction Pipeline (LLM)',
  'start_line': 1918,
  'end_line': 2141,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 15 · Document FAISS & Retrieval',
  'start_line': 2142,
  'end_line': 2261,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'},
 {'legacy_file': 'tests/test_memory_e2e.py',
  'heading': 'SECTION 16 · Document Cleanup & Source Deletion',
  'start_line': 2262,
  'end_line': 2498,
  'subsystem': 'knowledge_graph',
  'replacement_paths': ('tests/subsystem/knowledge_graph',
                        'tests/test_memory_recall_uplift.py',
                        'tests/test_knowledge_audit.py'),
  'status': 'covered',
  'verification_command': 'uv run python -m pytest tests/subsystem/knowledge_graph tests/test_memory_recall_uplift.py '
                          'tests/test_knowledge_audit.py -q',
  'notes': 'Migrated from legacy monolith before shrinking compatibility shims.'})
